[package]
name = "s1c1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "*"
base64 = "*"
lazy_static = "*"
hamming = "*"
aes = "*"